[versions]
agp = "8.7.3"
compose = "2.7.0"
desugar_jdk_libs = "2.1.5"
kotlin = "2.1.10"
ksp = "2.1.10-1.0.30"
coreKtx = "1.16.0"
junit = "4.13.2"
lifecycleRuntimeKtx = "2.9.1"
activityCompose = "1.10.1"
androidxHiltNavigationCompose = "1.2.0"
composeBom = "2025.06.01"
androidxNavigation = "2.9.0"
hilt = "2.53.1"
coroutinesTest = "1.10.1"
mockito = "5.4.0"
coreTesting = "2.2.0"
room = "2.7.2"
kotlinSerialization = "2.1.10"

[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
desugar_jdk_libs = { module = "com.android.tools:desugar_jdk_libs", version.ref = "desugar_jdk_libs" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "androidxNavigation" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-hilt-navigation-compose = { group = "androidx.hilt", name = "hilt-navigation-compose", version.ref = "androidxHiltNavigationCompose" }
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-android-compiler", version.ref = "hilt" }
androidx-core-testing =  { group = "androidx.arch.core", name = "core-testing", version.ref = "coreTesting" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "coroutinesTest" }
mockito =  { group = "org.mockito.kotlin", name = "mockito-kotlin", version.ref = "mockito" }
room = {group = "androidx.room", name="room-compiler", version.ref = "room" }
room-runtime = {group = "androidx.room", name="room-runtime", version.ref = "room" }
room-ktx = {group = "androidx.room", name="room-ktx", version.ref = "room" }
calendar-compose = { module = "com.kizitonwose.calendar:compose", version.ref = "compose" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
kotlin-serialization = {id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlinSerialization" }