package com.antsfamily.sexcalendar.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lightScheme = lightColorScheme(
    primary = Color(0xFFB60019),
    onPrimary = Color(0xFFffffff),
    primaryContainer = Color(0xFFAF001C),
    onPrimaryContainer = Color(0xFFFFBAB5),
    inversePrimary = Color(0xFFFFB3AE),
    secondary = Color(0xFFA23C3A),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFD817B),
    onSecondaryContainer = Color(0xFF73191B),
    tertiary = Color(0xFF5F3400),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFF804800),
    onTertiaryContainer = Color(0xFFFFBE82),
    surface = Color(0xFFFFF8F7),
    onSurface = Color(0xFF271716),
    onSurfaceVariant = Color(0xFF5C403E),
    inverseSurface = Color(0xFF3E2C2B),
    inverseOnSurface = Color(0xFFffEDEB),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000a),
    outline = Color(0xFF906f6d),
    outlineVariant = Color(0xFFE4BDBA),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainer = Color(0xFFFFE9E7),
    surfaceContainerHigh = Color(0xFFFFE1DF),
    surfaceContainerHighest = Color(0xFFfADCD9),
    surfaceContainerLow = Color(0xFFFFF0EF),
    surfaceContainerLowest = Color(0xFFffffff),
    surfaceDim = Color(0xFFF1D3D1)
)

val darkScheme = darkColorScheme(
    primary = Color(0xFFFFB3AE),
    onPrimary = Color(0xFF68000C),
    primaryContainer = Color(0xFFAF001C),
    onPrimaryContainer = Color(0xFFFFBAB5),
    inversePrimary = Color(0xFFbc1224),
    secondary = Color(0xFFffb3ae),
    onSecondary = Color(0xFF630c11),
    secondaryContainer = Color(0xFF862727),
    onSecondaryContainer = Color(0xFFff9e99),
    tertiary = Color(0xFFffb874),
    onTertiary = Color(0xFF4b2800),
    tertiaryContainer = Color(0xFFc98136),
    onTertiaryContainer = Color(0xFF422300),
    surface = Color(0xFF1e0f0e),
    onSurface = Color(0xFFfadcd9),
    onSurfaceVariant = Color(0xFFe4bdba),
    inverseSurface = Color(0xFFfadcd9),
    inverseOnSurface = Color(0xFF3E2C2B),
    error = Color(0xFFffb4ab),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000a),
    onErrorContainer = Color(0xFFffdad6),
    outline = Color(0xFFab8886),
    outlineVariant = Color(0xFF5C403E),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF483433),
    surfaceContainer = Color(0xFF2c1b1a),
    surfaceContainerHigh = Color(0xFF372524),
    surfaceContainerHighest = Color(0xFF43302f),
    surfaceContainerLow = Color(0xFF271716),
    surfaceContainerLowest = Color(0xFF190a09),
    surfaceDim = Color(0xFF1E0F0E),
)