package com.antsfamily.naughtynotes.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lightScheme = lightColorScheme(
    primary = Color(0xFFC9207A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFFFD9E2),
    onPrimaryContainer = Color(0xFF3E0021),
    inversePrimary = Color(0xFFFFB3AE),
    secondary = Color(0xFFA84D79),
    onSecondary = Color(0xFFFFFFFF),
    secondaryContainer = Color(0xFFFFD9E2),
    onSecondaryContainer = Color(0xFF3E0021),
    tertiary = Color(0xFF4A675D),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCCEBE0),
    onTertiaryContainer = Color(0xFF07201A),
    surface = Color(0xFFF8F8F8),
    onSurface = Color(0xFF000000),
    onSurfaceVariant = Color(0xFF5F5560),
    inverseSurface = Color(0xFF3E2C2B),
    inverseOnSurface = Color(0xFFffEDEB),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF9A8A93),
    outlineVariant = Color(0xFFE4BDBA),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainer = Color(0xFFFFFFFF),
    surfaceContainerHigh = Color(0xFFFFE1DF),
    surfaceContainerHighest = Color(0xFFFADCD9),
    surfaceContainerLow = Color(0xFFFFF0EF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFF1D3D1)
)

val darkScheme = darkColorScheme(
    primary = Color(0xFFFFB1C8),
    onPrimary = Color(0xFF5E0031),
    primaryContainer = Color(0xFF8E004A),
    onPrimaryContainer = Color(0xFFFFD9E2),
    inversePrimary = Color(0xFFC9207A),
    secondary = Color(0xFFE5BBD0),
    onSecondary = Color(0xFF432737),
    secondaryContainer = Color(0xFF5C3D4E),
    onSecondaryContainer = Color(0xFFFFD9E2),
    tertiary = Color(0xFFB1D1C5),
    onTertiary = Color(0xFF1C382F),
    tertiaryContainer = Color(0xFF334F45),
    onTertiaryContainer = Color(0xFFCCEBE0),
    surface = Color(0xFF171717),
    onSurface = Color(0xFFFFFFFF),
    onSurfaceVariant = Color(0xFFF1F1F1),
    inverseSurface = Color(0xFFFADCD9),
    inverseOnSurface = Color(0xFF3E2C2B),
    error = Color(0xFFFFB4AB),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000A),
    onErrorContainer = Color(0xFFFFDAD6),
    outline = Color(0xFF9F8C90),
    outlineVariant = Color(0xFF524346),
    scrim = Color(0xFF000000),
    surfaceBright = Color(0xFF3F3738),
    surfaceContainer = Color(0xFF202020),
    surfaceContainerHigh = Color(0xFF464646),
    surfaceContainerHighest = Color(0xFF43302F),
    surfaceContainerLow = Color(0xFF292929),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceDim = Color(0xFF1E0F0E),
)
