package com.antsfamily.naughtynotes.ui.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

val lightScheme = lightColorScheme(
    primary = Color(0xFFC9207A),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFC9207A),
    onPrimaryContainer = Color(0xFFFFBAB5),
    inversePrimary = Color(0xFFFFB3AE),
    secondary = Color(0xFFF1E532),
    onSecondary = Color(0xFF000000),
    secondaryContainer = Color(0xFFFD817B),
    onSecondaryContainer = Color(0xFF73191B),
    tertiary = Color(0xFF5F3400),
    onTertiary = Color(0xFFFFFFFF),
    tertiaryContainer = Color(0xFFCA320A),
    onTertiaryContainer = Color(0xFFFFFFFF),
    surface = Color(0xFFF8F8F8),
    onSurface = Color(0xFF000000),
    onSurfaceVariant = Color(0xFF303030),
    inverseSurface = Color(0xFF3E2C2B),
    inverseOnSurface = Color(0xFFffEDEB),
    error = Color(0xFFBA1A1A),
    onError = Color(0xFFFFFFFF),
    errorContainer = Color(0xFFFFDAD6),
    onErrorContainer = Color(0xFF93000A),
    outline = Color(0xFF906F6D),
    outlineVariant = Color(0xFFE4BDBA),
    scrim = Color(0xFFFBFBFB),
    surfaceBright = Color(0xFFFFF8F7),
    surfaceContainer = Color(0xFFFFFFFF),
    surfaceContainerHigh = Color(0xFFFFE1DF),
    surfaceContainerHighest = Color(0xFFFADCD9),
    surfaceContainerLow = Color(0xFFFFF0EF),
    surfaceContainerLowest = Color(0xFFFFFFFF),
    surfaceDim = Color(0xFFF1D3D1)
)

val darkScheme = darkColorScheme(
    primary = Color(0xFFb31c6d),
    onPrimary = Color(0xFFFFFFFF),
    primaryContainer = Color(0xFFb31c6d),
    onPrimaryContainer = Color(0xFFFFBAB5),
    inversePrimary = Color(0xFFbc1224),
    secondary = Color(0xFFF1E532),
    onSecondary = Color(0xFF000000),
    secondaryContainer = Color(0xFF862727),
    onSecondaryContainer = Color(0xFFff9e99),
    tertiary = Color(0xFFffb874),
    onTertiary = Color(0xFF4b2800),
    tertiaryContainer = Color(0xFFFE572F),
    onTertiaryContainer = Color(0xFF000000),
    surface = Color(0xFF171717),
    onSurface = Color(0xFFFFFFFF),
    onSurfaceVariant = Color(0xFFF1F1F1),
    inverseSurface = Color(0xFFfadcd9),
    inverseOnSurface = Color(0xFF3E2C2B),
    error = Color(0xFFffb4ab),
    onError = Color(0xFF690005),
    errorContainer = Color(0xFF93000a),
    onErrorContainer = Color(0xFFffdad6),
    outline = Color(0xFFab8886),
    outlineVariant = Color(0xFF5C403E),
    scrim = Color(0xFF171717),
    surfaceBright = Color(0xFF483433),
    surfaceContainer = Color(0xFF202020),
    surfaceContainerHigh = Color(0xFF464646),
    surfaceContainerHighest = Color(0xFF43302f),
    surfaceContainerLow = Color(0xFF292929),
    surfaceContainerLowest = Color(0xFF000000),
    surfaceDim = Color(0xFF1E0F0E),
)